os:
  - linux

sudo: required

services:
  - docker

language: go

go:
  - 1.11.x

script:
  - GO111MODULE=on go get github.com/mritd/gcrsync
  - gcrsync sync --querylimit 20 --processlimit 10 --httptimeout 10s --user ${DOCKER_USER} --password ${DOCKER_PASSWORD} --githubtoken ${GITHUB_TOKEN} --namespace kubeflow-images-public
